apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namePrefix: dev-
secretGenerator:
    - name:  secret
      literals:
      - DB_URL='dev_url'
      - DB_USER='dev_user' 