apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namePrefix: prod-
secretGenerator:
    - name:  secret
      literals:
      - DB_URL='prod_url'
      - DB_USER='prod_user'
images:      
  - name: iliefa/samples
    newTag: prod
patches:
  - path: imagepullpolicy.yaml
    target:
      kind: Deployment
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: ingress-sample
    path: ingress_patch.json