---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: springboot-sample
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: springboot-sample
      template:
        metadata:
          labels:
            app: springboot-sample
        spec:
          containers:
          - name: springboot-sample
            image: iliefa/samples:v1
            ports:
            - containerPort: 8080
            livenessProbe:
              httpGet:
                port: 8080
                path: /actuator/health
            readinessProbe:
              httpGet:
                port: 8080
                path: /actuator/health
            envFrom:
              - secretRef:
                  name: secret
